### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by KirillLykov** [travisdowns/sort-bench#1]
It seems that there is no license information for this repo and, more importantly, for `radix_sort7`.
Could you add one?
It was discussed in the context of developing a stable integers sort for Apache Arrow project, see [jira issue](https://issues.apache.org/jira/browse/ARROW-10899#)

**Comment by travisdowns** [comment]
Thanks for the report, and good catch: I do try to add licenses for most of my projects. 

I will make this available under MIT as soon as I get a moment. Is that compatible with the Arrow license?

**Comment by travisdowns** [comment]
@KirillLykov - it's MIT licensed now.
